//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrival
    {
        public int Arrival_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> BeingLate_ID { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<bool> Came { get; set; }
    
        public virtual BeingLate BeingLate { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
